version: "3.6"

services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
    ports:
      - "54320:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  webpack:
    build:
      context: "."
      dockerfile: "Dockerfile.webpack"
    command: npm run watch
    volumes:
      - .:/opt/app
      - static:/opt/app/priv/static
      - node_modules:/opt/app/assets/node_modules

  app:
    build:
      context: .
      target: phoenix_base
    command: mix do deps.get, phx.server
    healthcheck:
      interval: 5m
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
    volumes:
      - .:/opt/app
      - static:/opt/app/priv/static
    depends_on:
      - db
      - webpack

volumes:
  pg_data:
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
  node_modules:
