version: "3.6"

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
    ports:
      - "54320:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: phoenix_base
    command: mix phx.server
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pg_data:
