version: "3.6"

services:
  test:
    build:
      context: .
      target: phoenix_base
    command: mix do deps.get, test
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
