version: "3.6"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
    ports:
      - "54320:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: phoenix_base
    command: mix do deps.get, phx.server
    healthcheck:
      interval: 5m
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
      MIX_BUILD_PATH: /opt/mix/build
      MIX_DEPS_PATH: /opt/mix/deps
    volumes:
      - .:/opt/app
      - mix_build:/opt/mix/build
      - mix_deps:/opt/mix/deps
    depends_on:
      - db

volumes:
  pg_data:
  mix_build:
  mix_deps:
