version: "3.6"

services:
  test:
    build:
      context: .
      target: phoenix_dev
    command: mix test
    environment:
      MIX_ENV: test
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
