version: "3.6"

services:
  app:
    build:
      context: .
      target: phoenix_base
    command: mix phx.server
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASS: letmein
      SITA_API_KEY: KEY_GOES_HERE
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: letmein
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
