version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run tests
          command: docker-compose -f docker-compose.test.yml run --rm test

  build-release:
    docker:
      - image: circleci/buildpack-deps
    working_directory: ~/repo
    steps:
      - run:
          name: Build release image
          command: docker build --target myflightmap_prod --tag myflightmap3:latest .
      - run:
          name: Tag release image
          command: docker tag myflightmap3:latest mfroach/myflightmap3

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Push to Docker Hub
          command: docker push mfroach/myflightmap3

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - build-release:
          requires:
            - build
          filters:
            branches:
              only: production
